#pragma once

#include "core/App.h"
#include "core/Common.h"
#include "core/GameObject.h"
#include "core/GameObjectManager.h"
#include "core/Types.h"

#include "render/BufferManager.h"
#include "render/Buffer.h"
#include "render/IndexBuffer.h"
#include "render/Program.h"
#include "render/ProgramManager.h"
#include "render/VertexBuffer.h"
#include "render/VertexDeclaration.h"
#include "render/Texture.h"
#include "render/TextureManager.h"
#include "render/RenderTarget.h"
#include "render/Material.h"
#include "render/MaterialManager.h"
#include "render/Model.h"
#include "render/SkinnedModel.h"
